# To customize EnvoyProxy
# https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: aibrix-custom-proxy-config
  namespace: aibrix-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                  - name: envoy
                    resources:
                      requests:
                        cpu: 2
                        memory: 8Gi
                      limits:
                        cpu: 2
                        memory: 8Gi