resources:
  - ../templates/deployment
  - components.yaml
  - config-profile.yaml
  - vllm-pd-config.yaml
  - vllm-pd-bucketing-config.yaml
  - sglang-pd-config.yaml
  - trtllm-pd-config.yaml

patches:
  - path: api-key-patch.yaml