/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RoleSpecApplyConfiguration represents a declarative configuration of the RoleSpec type for use
// with apply.
type RoleSpecApplyConfiguration struct {
	Name                *string                                `json:"name,omitempty"`
	Replicas            *int32                                 `json:"replicas,omitempty"`
	Drain               *RoleDrainSpecApplyConfiguration       `json:"drain,omitempty"`
	UpgradeOrder        *int32                                 `json:"upgradeOrder,omitempty"`
	PodGroupSize        *int32                                 `json:"podGroupSize,omitempty"`
	UpdateStrategy      *RoleUpdateStrategyApplyConfiguration  `json:"updateStrategy,omitempty"`
	Stateful            *bool                                  `json:"stateful,omitempty"`
	Template            *v1.PodTemplateSpec                    `json:"template,omitempty"`
	DisruptionTolerance *DisruptionToleranceApplyConfiguration `json:"disruptionTolerance,omitempty"`
	SchedulingStrategy  *SchedulingStrategyApplyConfiguration  `json:"schedulingStrategy,omitempty"`
}

// RoleSpecApplyConfiguration constructs a declarative configuration of the RoleSpec type for use with
// apply.
func RoleSpec() *RoleSpecApplyConfiguration {
	return &RoleSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithName(value string) *RoleSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithReplicas(value int32) *RoleSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithDrain sets the Drain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Drain field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithDrain(value *RoleDrainSpecApplyConfiguration) *RoleSpecApplyConfiguration {
	b.Drain = value
	return b
}

// WithUpgradeOrder sets the UpgradeOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeOrder field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithUpgradeOrder(value int32) *RoleSpecApplyConfiguration {
	b.UpgradeOrder = &value
	return b
}

// WithPodGroupSize sets the PodGroupSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupSize field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithPodGroupSize(value int32) *RoleSpecApplyConfiguration {
	b.PodGroupSize = &value
	return b
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithUpdateStrategy(value *RoleUpdateStrategyApplyConfiguration) *RoleSpecApplyConfiguration {
	b.UpdateStrategy = value
	return b
}

// WithStateful sets the Stateful field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stateful field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithStateful(value bool) *RoleSpecApplyConfiguration {
	b.Stateful = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithTemplate(value v1.PodTemplateSpec) *RoleSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithDisruptionTolerance sets the DisruptionTolerance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionTolerance field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithDisruptionTolerance(value *DisruptionToleranceApplyConfiguration) *RoleSpecApplyConfiguration {
	b.DisruptionTolerance = value
	return b
}

// WithSchedulingStrategy sets the SchedulingStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingStrategy field is set to the value of the last call.
func (b *RoleSpecApplyConfiguration) WithSchedulingStrategy(value *SchedulingStrategyApplyConfiguration) *RoleSpecApplyConfiguration {
	b.SchedulingStrategy = value
	return b
}
