/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/orchestration/v1alpha1"
)

// TopologyPolicyApplyConfiguration represents a declarative configuration of the TopologyPolicy type for use
// with apply.
type TopologyPolicyApplyConfiguration struct {
	Scope *v1alpha1.TopologyScope      `json:"scope,omitempty"`
	Mode  *v1alpha1.TopologyPolicyMode `json:"mode,omitempty"`
	Key   *string                      `json:"key,omitempty"`
}

// TopologyPolicyApplyConfiguration constructs a declarative configuration of the TopologyPolicy type for use with
// apply.
func TopologyPolicy() *TopologyPolicyApplyConfiguration {
	return &TopologyPolicyApplyConfiguration{}
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *TopologyPolicyApplyConfiguration) WithScope(value v1alpha1.TopologyScope) *TopologyPolicyApplyConfiguration {
	b.Scope = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TopologyPolicyApplyConfiguration) WithMode(value v1alpha1.TopologyPolicyMode) *TopologyPolicyApplyConfiguration {
	b.Mode = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *TopologyPolicyApplyConfiguration) WithKey(value string) *TopologyPolicyApplyConfiguration {
	b.Key = &value
	return b
}
