/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/aibrix/aibrix/api/model/v1alpha1"
	modelv1alpha1 "github.com/aibrix/aibrix/pkg/client/applyconfiguration/model/v1alpha1"
	scheme "github.com/aibrix/aibrix/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ModelAdaptersGetter has a method to return a ModelAdapterInterface.
// A group's client should implement this interface.
type ModelAdaptersGetter interface {
	ModelAdapters(namespace string) ModelAdapterInterface
}

// ModelAdapterInterface has methods to work with ModelAdapter resources.
type ModelAdapterInterface interface {
	Create(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.CreateOptions) (*v1alpha1.ModelAdapter, error)
	Update(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.UpdateOptions) (*v1alpha1.ModelAdapter, error)
	UpdateStatus(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.UpdateOptions) (*v1alpha1.ModelAdapter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ModelAdapter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ModelAdapterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelAdapter, err error)
	Apply(ctx context.Context, modelAdapter *modelv1alpha1.ModelAdapterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelAdapter, err error)
	ApplyStatus(ctx context.Context, modelAdapter *modelv1alpha1.ModelAdapterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelAdapter, err error)
	ModelAdapterExpansion
}

// modelAdapters implements ModelAdapterInterface
type modelAdapters struct {
	client rest.Interface
	ns     string
}

// newModelAdapters returns a ModelAdapters
func newModelAdapters(c *ModelV1alpha1Client, namespace string) *modelAdapters {
	return &modelAdapters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the modelAdapter, and returns the corresponding modelAdapter object, and an error if there is any.
func (c *modelAdapters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModelAdapter, err error) {
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modeladapters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ModelAdapters that match those selectors.
func (c *modelAdapters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModelAdapterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ModelAdapterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modeladapters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested modelAdapters.
func (c *modelAdapters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("modeladapters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a modelAdapter and creates it.  Returns the server's representation of the modelAdapter, and an error, if there is any.
func (c *modelAdapters) Create(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.CreateOptions) (result *v1alpha1.ModelAdapter, err error) {
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("modeladapters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelAdapter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a modelAdapter and updates it. Returns the server's representation of the modelAdapter, and an error, if there is any.
func (c *modelAdapters) Update(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.UpdateOptions) (result *v1alpha1.ModelAdapter, err error) {
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("modeladapters").
		Name(modelAdapter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelAdapter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *modelAdapters) UpdateStatus(ctx context.Context, modelAdapter *v1alpha1.ModelAdapter, opts v1.UpdateOptions) (result *v1alpha1.ModelAdapter, err error) {
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("modeladapters").
		Name(modelAdapter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelAdapter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the modelAdapter and deletes it. Returns an error if one occurs.
func (c *modelAdapters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modeladapters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *modelAdapters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modeladapters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched modelAdapter.
func (c *modelAdapters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelAdapter, err error) {
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("modeladapters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied modelAdapter.
func (c *modelAdapters) Apply(ctx context.Context, modelAdapter *modelv1alpha1.ModelAdapterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelAdapter, err error) {
	if modelAdapter == nil {
		return nil, fmt.Errorf("modelAdapter provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(modelAdapter)
	if err != nil {
		return nil, err
	}
	name := modelAdapter.Name
	if name == nil {
		return nil, fmt.Errorf("modelAdapter.Name must be provided to Apply")
	}
	result = &v1alpha1.ModelAdapter{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("modeladapters").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *modelAdapters) ApplyStatus(ctx context.Context, modelAdapter *modelv1alpha1.ModelAdapterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelAdapter, err error) {
	if modelAdapter == nil {
		return nil, fmt.Errorf("modelAdapter provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(modelAdapter)
	if err != nil {
		return nil, err
	}

	name := modelAdapter.Name
	if name == nil {
		return nil, fmt.Errorf("modelAdapter.Name must be provided to Apply")
	}

	result = &v1alpha1.ModelAdapter{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("modeladapters").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
