apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aibrix-system

resources:
  - ../namespace
  - ../metadata
  - metadata-batch-rbac.yaml
  - storage.yaml
  - console.yaml
  - prometheus.yaml
  - grafana.yaml

patches:
  - path: metadata-s3-env-patch.yaml
  - path: metadata-local-patch.yaml

configMapGenerator:
  - name: batch-prometheus-config
    files:
      - prometheus.yml=prometheus-config.yaml
  - name: batch-grafana-datasources
    files:
      - datasource.yaml=grafana-datasource.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: metadata-service
    newName: aibrix/metadata-service
    newTag: nightly
  - name: redis
    newName: redis
    newTag: latest
  - name: busybox
    newName: busybox
    newTag: stable
  - name: aibrix-console
    newName: aibrix/console
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: aibrix
      app.kubernetes.io/version: nightly
      app.kubernetes.io/managed-by: kubectl
