/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodAutoscalerScheduleApplyConfiguration represents a declarative configuration of the PodAutoscalerSchedule type for use
// with apply.
type PodAutoscalerScheduleApplyConfiguration struct {
	Name        *string  `json:"name,omitempty"`
	Timezone    *string  `json:"timezone,omitempty"`
	DaysOfWeek  []string `json:"daysOfWeek,omitempty"`
	StartTime   *string  `json:"startTime,omitempty"`
	EndTime     *string  `json:"endTime,omitempty"`
	MinReplicas *int32   `json:"minReplicas,omitempty"`
	MaxReplicas *int32   `json:"maxReplicas,omitempty"`
}

// PodAutoscalerScheduleApplyConfiguration constructs a declarative configuration of the PodAutoscalerSchedule type for use with
// apply.
func PodAutoscalerSchedule() *PodAutoscalerScheduleApplyConfiguration {
	return &PodAutoscalerScheduleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithName(value string) *PodAutoscalerScheduleApplyConfiguration {
	b.Name = &value
	return b
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithTimezone(value string) *PodAutoscalerScheduleApplyConfiguration {
	b.Timezone = &value
	return b
}

// WithDaysOfWeek adds the given value to the DaysOfWeek field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DaysOfWeek field.
func (b *PodAutoscalerScheduleApplyConfiguration) WithDaysOfWeek(values ...string) *PodAutoscalerScheduleApplyConfiguration {
	for i := range values {
		b.DaysOfWeek = append(b.DaysOfWeek, values[i])
	}
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithStartTime(value string) *PodAutoscalerScheduleApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithEndTime(value string) *PodAutoscalerScheduleApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithMinReplicas(value int32) *PodAutoscalerScheduleApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *PodAutoscalerScheduleApplyConfiguration) WithMaxReplicas(value int32) *PodAutoscalerScheduleApplyConfiguration {
	b.MaxReplicas = &value
	return b
}
