/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ScheduledBoundsStatusApplyConfiguration represents a declarative configuration of the ScheduledBoundsStatus type for use
// with apply.
type ScheduledBoundsStatusApplyConfiguration struct {
	ActiveSchedule       *string `json:"activeSchedule,omitempty"`
	EffectiveMinReplicas *int32  `json:"effectiveMinReplicas,omitempty"`
	EffectiveMaxReplicas *int32  `json:"effectiveMaxReplicas,omitempty"`
}

// ScheduledBoundsStatusApplyConfiguration constructs a declarative configuration of the ScheduledBoundsStatus type for use with
// apply.
func ScheduledBoundsStatus() *ScheduledBoundsStatusApplyConfiguration {
	return &ScheduledBoundsStatusApplyConfiguration{}
}

// WithActiveSchedule sets the ActiveSchedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveSchedule field is set to the value of the last call.
func (b *ScheduledBoundsStatusApplyConfiguration) WithActiveSchedule(value string) *ScheduledBoundsStatusApplyConfiguration {
	b.ActiveSchedule = &value
	return b
}

// WithEffectiveMinReplicas sets the EffectiveMinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveMinReplicas field is set to the value of the last call.
func (b *ScheduledBoundsStatusApplyConfiguration) WithEffectiveMinReplicas(value int32) *ScheduledBoundsStatusApplyConfiguration {
	b.EffectiveMinReplicas = &value
	return b
}

// WithEffectiveMaxReplicas sets the EffectiveMaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveMaxReplicas field is set to the value of the last call.
func (b *ScheduledBoundsStatusApplyConfiguration) WithEffectiveMaxReplicas(value int32) *ScheduledBoundsStatusApplyConfiguration {
	b.EffectiveMaxReplicas = &value
	return b
}
