apiVersion: model.aibrix.ai/v1alpha1
kind: ModelAdapter
metadata:
  name: text2sql-lora-1
  namespace: default
  labels:
    model.aibrix.ai/name: "text2sql-lora-1"
    model.aibrix.ai/port: "8000"
spec:
  baseModel: llama2-7b
  podSelector:
    matchLabels:
      model.aibrix.ai/name: llama2-7b
  artifactURL: huggingface://yard1/llama-2-7b-sql-lora-test
  schedulerName: default
