/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/aibrix/aibrix/api/orchestration/v1alpha1"
	orchestrationv1alpha1 "github.com/aibrix/aibrix/pkg/client/applyconfiguration/orchestration/v1alpha1"
	scheme "github.com/aibrix/aibrix/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RayClusterReplicaSetsGetter has a method to return a RayClusterReplicaSetInterface.
// A group's client should implement this interface.
type RayClusterReplicaSetsGetter interface {
	RayClusterReplicaSets(namespace string) RayClusterReplicaSetInterface
}

// RayClusterReplicaSetInterface has methods to work with RayClusterReplicaSet resources.
type RayClusterReplicaSetInterface interface {
	Create(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.CreateOptions) (*v1alpha1.RayClusterReplicaSet, error)
	Update(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.UpdateOptions) (*v1alpha1.RayClusterReplicaSet, error)
	UpdateStatus(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.UpdateOptions) (*v1alpha1.RayClusterReplicaSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RayClusterReplicaSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RayClusterReplicaSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RayClusterReplicaSet, err error)
	Apply(ctx context.Context, rayClusterReplicaSet *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RayClusterReplicaSet, err error)
	ApplyStatus(ctx context.Context, rayClusterReplicaSet *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RayClusterReplicaSet, err error)
	RayClusterReplicaSetExpansion
}

// rayClusterReplicaSets implements RayClusterReplicaSetInterface
type rayClusterReplicaSets struct {
	client rest.Interface
	ns     string
}

// newRayClusterReplicaSets returns a RayClusterReplicaSets
func newRayClusterReplicaSets(c *OrchestrationV1alpha1Client, namespace string) *rayClusterReplicaSets {
	return &rayClusterReplicaSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rayClusterReplicaSet, and returns the corresponding rayClusterReplicaSet object, and an error if there is any.
func (c *rayClusterReplicaSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RayClusterReplicaSets that match those selectors.
func (c *rayClusterReplicaSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RayClusterReplicaSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RayClusterReplicaSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rayClusterReplicaSets.
func (c *rayClusterReplicaSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rayClusterReplicaSet and creates it.  Returns the server's representation of the rayClusterReplicaSet, and an error, if there is any.
func (c *rayClusterReplicaSets) Create(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.CreateOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayClusterReplicaSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rayClusterReplicaSet and updates it. Returns the server's representation of the rayClusterReplicaSet, and an error, if there is any.
func (c *rayClusterReplicaSets) Update(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.UpdateOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(rayClusterReplicaSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayClusterReplicaSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rayClusterReplicaSets) UpdateStatus(ctx context.Context, rayClusterReplicaSet *v1alpha1.RayClusterReplicaSet, opts v1.UpdateOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(rayClusterReplicaSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayClusterReplicaSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rayClusterReplicaSet and deletes it. Returns an error if one occurs.
func (c *rayClusterReplicaSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rayClusterReplicaSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rayClusterReplicaSet.
func (c *rayClusterReplicaSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RayClusterReplicaSet, err error) {
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied rayClusterReplicaSet.
func (c *rayClusterReplicaSets) Apply(ctx context.Context, rayClusterReplicaSet *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	if rayClusterReplicaSet == nil {
		return nil, fmt.Errorf("rayClusterReplicaSet provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rayClusterReplicaSet)
	if err != nil {
		return nil, err
	}
	name := rayClusterReplicaSet.Name
	if name == nil {
		return nil, fmt.Errorf("rayClusterReplicaSet.Name must be provided to Apply")
	}
	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *rayClusterReplicaSets) ApplyStatus(ctx context.Context, rayClusterReplicaSet *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RayClusterReplicaSet, err error) {
	if rayClusterReplicaSet == nil {
		return nil, fmt.Errorf("rayClusterReplicaSet provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rayClusterReplicaSet)
	if err != nil {
		return nil, err
	}

	name := rayClusterReplicaSet.Name
	if name == nil {
		return nil, fmt.Errorf("rayClusterReplicaSet.Name must be provided to Apply")
	}

	result = &v1alpha1.RayClusterReplicaSet{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rayclusterreplicasets").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
