apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-extension
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-extension
  template:
    metadata:
      labels:
        app: api-extension
    spec:
      serviceAccountName: api-extension-sa
      automountServiceAccountToken: true
      containers:
      - name: api-extension
        image: aibrix/runtime:nightly
        command: 
        ports:
        - containerPort: 8100
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        env:
          - name: REDIS_HOST
            value: aibrix-redis-master.aibrix-system.svc.cluster.local