/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/aibrix/aibrix/api/orchestration/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RayClusterFleetLister helps list RayClusterFleets.
// All objects returned here must be treated as read-only.
type RayClusterFleetLister interface {
	// List lists all RayClusterFleets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RayClusterFleet, err error)
	// RayClusterFleets returns an object that can list and get RayClusterFleets.
	RayClusterFleets(namespace string) RayClusterFleetNamespaceLister
	RayClusterFleetListerExpansion
}

// rayClusterFleetLister implements the RayClusterFleetLister interface.
type rayClusterFleetLister struct {
	indexer cache.Indexer
}

// NewRayClusterFleetLister returns a new RayClusterFleetLister.
func NewRayClusterFleetLister(indexer cache.Indexer) RayClusterFleetLister {
	return &rayClusterFleetLister{indexer: indexer}
}

// List lists all RayClusterFleets in the indexer.
func (s *rayClusterFleetLister) List(selector labels.Selector) (ret []*v1alpha1.RayClusterFleet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RayClusterFleet))
	})
	return ret, err
}

// RayClusterFleets returns an object that can list and get RayClusterFleets.
func (s *rayClusterFleetLister) RayClusterFleets(namespace string) RayClusterFleetNamespaceLister {
	return rayClusterFleetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RayClusterFleetNamespaceLister helps list and get RayClusterFleets.
// All objects returned here must be treated as read-only.
type RayClusterFleetNamespaceLister interface {
	// List lists all RayClusterFleets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RayClusterFleet, err error)
	// Get retrieves the RayClusterFleet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RayClusterFleet, error)
	RayClusterFleetNamespaceListerExpansion
}

// rayClusterFleetNamespaceLister implements the RayClusterFleetNamespaceLister
// interface.
type rayClusterFleetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RayClusterFleets in the indexer for a given namespace.
func (s rayClusterFleetNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RayClusterFleet, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RayClusterFleet))
	})
	return ret, err
}

// Get retrieves the RayClusterFleet from the indexer for a given namespace and name.
func (s rayClusterFleetNamespaceLister) Get(name string) (*v1alpha1.RayClusterFleet, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("rayclusterfleet"), name)
	}
	return obj.(*v1alpha1.RayClusterFleet), nil
}
