/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	orchestrationv1alpha1 "github.com/aibrix/aibrix/api/orchestration/v1alpha1"
	versioned "github.com/aibrix/aibrix/pkg/client/clientset/versioned"
	internalinterfaces "github.com/aibrix/aibrix/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/aibrix/aibrix/pkg/client/listers/orchestration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RayClusterReplicaSetInformer provides access to a shared informer and lister for
// RayClusterReplicaSets.
type RayClusterReplicaSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RayClusterReplicaSetLister
}

type rayClusterReplicaSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRayClusterReplicaSetInformer constructs a new informer for RayClusterReplicaSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRayClusterReplicaSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRayClusterReplicaSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRayClusterReplicaSetInformer constructs a new informer for RayClusterReplicaSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRayClusterReplicaSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OrchestrationV1alpha1().RayClusterReplicaSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OrchestrationV1alpha1().RayClusterReplicaSets(namespace).Watch(context.TODO(), options)
			},
		},
		&orchestrationv1alpha1.RayClusterReplicaSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *rayClusterReplicaSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRayClusterReplicaSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rayClusterReplicaSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&orchestrationv1alpha1.RayClusterReplicaSet{}, f.defaultInformer)
}

func (f *rayClusterReplicaSetInformer) Lister() v1alpha1.RayClusterReplicaSetLister {
	return v1alpha1.NewRayClusterReplicaSetLister(f.Informer().GetIndexer())
}
