apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../crd/orchestration
  - ../../rbac/orchestration
  - ../../rbac/controller-manager
  - ../../manager

# Adds namespace to all resources.
namespace: aibrix-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: aibrix-kv-cache-

images:
  - name: controller
    newName: aibrix/controller-manager
    newTag: nightly

patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager

labels:
  - pairs:
      app.kubernetes.io/name: aibrix
      app.kubernetes.io/component: aibrix-kvcache-controller
      app.kubernetes.io/version: nightly
      app.kubernetes.io/managed-by: kubectl
